---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  lint-hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run Hadolint
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: "./Dockerfile"
    
  lint-shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run Shellcheck
        uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: -s bash

  lint-markdown:
    name: MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run mdl
        uses: actionshub/markdownlint@2.0.2

  build:
    name: Build
    needs:
      - lint-hadolint
      - lint-shellcheck
      - lint-markdown
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: 🚀 Build
        uses: docker/build-push-action@v2.3.0
        with:
          push: false
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          build-args: |
            BUILD_DATE=${{ steps.flags.outputs.date }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}

